name: .NET

on:
  push:
   branches-ignore:
    - main
     
  pull_request:
    branches:
    - main
    - develop
    - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore AnimeRouletteAPI.sln
    - name: Build
      run: dotnet build --no-restore AnimeRouletteAPI.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
